export const CATEGORIES = [
    {
        id:0,
        name:"Fruit",
        image:require("../assets/imageCategories/Fruit.png"), 
    },
    {
        id:1,
        name:"Vegetables",
        image:require("../assets/imageCategories/Vegetables.png"),
    },
    {
        id:2,
        name:"Dairy",
        image:require("../assets/imageCategories/Dairy.png"),
    },
    {
        id:3,
        name:"Cheese",
        image:require("../assets/imageCategories/Cheese.png"),
    },
    {
        id:4,
        name:"Meat",
        image:require("../assets/imageCategories/Meat.png"),
    },
    {
        id:5,
        name:"Fish",
        image:require("../assets/imageCategories/Fish.png"),
    },
    {
        id:6,
        name:"Beverage",
        image:require("../assets/imageCategories/Beverage.png"),
    },
    {
        id:7,
        name:"Wine",
        image:require("../assets/imageCategories/Wine.png"),
    }
]